# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'carritos.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.setEnabled(True)
        Form.resize(869, 697)
        Form.setMinimumSize(QtCore.QSize(869, 697))
        Form.setMaximumSize(QtCore.QSize(869, 697))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 159, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(196, 225, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(155, 192, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 79, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 106, 138))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 52, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 159, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 207, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 159, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(196, 225, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(155, 192, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 79, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 106, 138))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 52, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 159, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 207, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 79, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 159, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(196, 225, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(155, 192, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 79, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 106, 138))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 79, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 79, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 159, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 159, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        Form.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        Form.setFont(font)
        Form.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../assets/imagenes/carritos_icono_32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setToolTip("")
        Form.setToolTipDuration(2)
        self.toolBox_inicio = QtWidgets.QToolBox(Form)
        self.toolBox_inicio.setGeometry(QtCore.QRect(20, 20, 842, 631))
        self.toolBox_inicio.setAutoFillBackground(True)
        self.toolBox_inicio.setObjectName("toolBox_inicio")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 842, 476))
        self.page_5.setObjectName("page_5")
        self.pushButton_acercade = QtWidgets.QPushButton(self.page_5)
        self.pushButton_acercade.setGeometry(QtCore.QRect(710, 410, 80, 25))
        self.pushButton_acercade.setObjectName("pushButton_acercade")
        self.label_inicio = QtWidgets.QLabel(self.page_5)
        self.label_inicio.setGeometry(QtCore.QRect(240, 60, 341, 341))
        self.label_inicio.setLineWidth(0)
        self.label_inicio.setText("")
        self.label_inicio.setTextFormat(QtCore.Qt.PlainText)
        self.label_inicio.setPixmap(QtGui.QPixmap("logo-consejeria-educacion.png"))
        self.label_inicio.setScaledContents(True)
        self.label_inicio.setObjectName("label_inicio")
        self.toolBox_inicio.addItem(self.page_5, "")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 842, 476))
        self.page.setObjectName("page")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.page)
        self.calendarWidget.setGeometry(QtCore.QRect(0, 10, 451, 471))
        self.calendarWidget.setAutoFillBackground(False)
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setSelectionMode(QtWidgets.QCalendarWidget.SingleSelection)
        self.calendarWidget.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.ShortDayNames)
        self.calendarWidget.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget.setNavigationBarVisible(True)
        self.calendarWidget.setDateEditEnabled(True)
        self.calendarWidget.setObjectName("calendarWidget")
        self.groupBox = QtWidgets.QGroupBox(self.page)
        self.groupBox.setGeometry(QtCore.QRect(460, 220, 381, 251))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_1 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_1.setGeometry(QtCore.QRect(10, 30, 91, 31))
        self.pushButton_1.setFlat(False)
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 60, 91, 31))
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setCheckable(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 90, 91, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_RECREO = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_RECREO.setGeometry(QtCore.QRect(10, 120, 91, 31))
        self.pushButton_RECREO.setObjectName("pushButton_RECREO")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 210, 91, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 150, 91, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 180, 91, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.plainTextEdit_1 = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit_1.setGeometry(QtCore.QRect(110, 30, 261, 31))
        self.plainTextEdit_1.setReadOnly(True)
        self.plainTextEdit_1.setObjectName("plainTextEdit_1")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(110, 60, 261, 31))
        self.plainTextEdit_2.setReadOnly(True)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(110, 90, 261, 31))
        self.plainTextEdit_3.setReadOnly(True)
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.plainTextEdit_RECREO = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit_RECREO.setGeometry(QtCore.QRect(110, 120, 261, 31))
        self.plainTextEdit_RECREO.setReadOnly(True)
        self.plainTextEdit_RECREO.setObjectName("plainTextEdit_RECREO")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(110, 150, 261, 31))
        self.plainTextEdit_4.setReadOnly(True)
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.plainTextEdit_5 = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit_5.setGeometry(QtCore.QRect(110, 180, 261, 31))
        self.plainTextEdit_5.setReadOnly(True)
        self.plainTextEdit_5.setObjectName("plainTextEdit_5")
        self.plainTextEdit_6 = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit_6.setGeometry(QtCore.QRect(110, 210, 261, 31))
        self.plainTextEdit_6.setReadOnly(True)
        self.plainTextEdit_6.setObjectName("plainTextEdit_6")
        self.groupBox_2 = QtWidgets.QGroupBox(self.page)
        self.groupBox_2.setGeometry(QtCore.QRect(460, 0, 381, 211))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 40, 61, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(190, 40, 61, 31))
        self.label_2.setObjectName("label_2")
        self.comboBox_planta = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_planta.setGeometry(QtCore.QRect(70, 40, 111, 31))
        self.comboBox_planta.setObjectName("comboBox_planta")
        self.comboBox_carrito = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_carrito.setGeometry(QtCore.QRect(250, 40, 121, 31))
        self.comboBox_carrito.setObjectName("comboBox_carrito")
        self.plainTextEdit_info = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.plainTextEdit_info.setGeometry(QtCore.QRect(10, 80, 361, 131))
        self.plainTextEdit_info.setReadOnly(True)
        self.plainTextEdit_info.setObjectName("plainTextEdit_info")
        self.toolBox_inicio.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 842, 476))
        self.page_2.setObjectName("page_2")
        self.tableWidget_incidencia = QtWidgets.QTableWidget(self.page_2)
        self.tableWidget_incidencia.setGeometry(QtCore.QRect(0, 0, 831, 411))
        self.tableWidget_incidencia.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_incidencia.setAlternatingRowColors(True)
        self.tableWidget_incidencia.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_incidencia.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_incidencia.setShowGrid(True)
        self.tableWidget_incidencia.setColumnCount(13)
        self.tableWidget_incidencia.setObjectName("tableWidget_incidencia")
        self.tableWidget_incidencia.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_incidencia.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_incidencia.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_incidencia.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_incidencia.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_incidencia.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_incidencia.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_incidencia.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_incidencia.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_incidencia.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_incidencia.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_incidencia.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_incidencia.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_incidencia.setHorizontalHeaderItem(12, item)
        self.tableWidget_incidencia.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_incidencia.verticalHeader().setSortIndicatorShown(True)
        self.pushButton_crear_incid = QtWidgets.QPushButton(self.page_2)
        self.pushButton_crear_incid.setGeometry(QtCore.QRect(620, 430, 211, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.pushButton_crear_incid.setFont(font)
        self.pushButton_crear_incid.setDefault(True)
        self.pushButton_crear_incid.setObjectName("pushButton_crear_incid")
        self.toolBox_inicio.addItem(self.page_2, "")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 842, 476))
        self.page_4.setObjectName("page_4")
        self.toolBox_inicio.addItem(self.page_4, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 842, 476))
        self.page_3.setObjectName("page_3")
        self.tabWidget_conf = QtWidgets.QTabWidget(self.page_3)
        self.tabWidget_conf.setGeometry(QtCore.QRect(0, 0, 841, 421))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 159, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(196, 225, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(155, 192, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 79, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 106, 138))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 159, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 207, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 159, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(196, 225, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(155, 192, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 79, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 106, 138))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 159, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 207, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 79, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 159, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(196, 225, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(155, 192, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 79, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 106, 138))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 79, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 79, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 159, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 159, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 159, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.tabWidget_conf.setPalette(palette)
        self.tabWidget_conf.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget_conf.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget_conf.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget_conf.setUsesScrollButtons(False)
        self.tabWidget_conf.setDocumentMode(False)
        self.tabWidget_conf.setTabsClosable(False)
        self.tabWidget_conf.setObjectName("tabWidget_conf")
        self.tab_profesorado = QtWidgets.QWidget()
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 159, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(196, 225, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(155, 192, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 79, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 106, 138))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 159, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 207, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 159, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(196, 225, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(155, 192, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 79, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 106, 138))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 159, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 207, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 79, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 159, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(196, 225, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(155, 192, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 79, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 106, 138))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 79, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 79, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 159, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 159, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 159, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.tab_profesorado.setPalette(palette)
        self.tab_profesorado.setObjectName("tab_profesorado")
        self.tableWidget_profesorado = QtWidgets.QTableWidget(self.tab_profesorado)
        self.tableWidget_profesorado.setGeometry(QtCore.QRect(20, 20, 771, 381))
        self.tableWidget_profesorado.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_profesorado.setAlternatingRowColors(True)
        self.tableWidget_profesorado.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_profesorado.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_profesorado.setObjectName("tableWidget_profesorado")
        self.tableWidget_profesorado.setColumnCount(2)
        self.tableWidget_profesorado.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_profesorado.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_profesorado.setHorizontalHeaderItem(1, item)
        self.tabWidget_conf.addTab(self.tab_profesorado, "")
        self.tab_planta = QtWidgets.QWidget()
        self.tab_planta.setAutoFillBackground(False)
        self.tab_planta.setObjectName("tab_planta")
        self.tableWidget_planta = QtWidgets.QTableWidget(self.tab_planta)
        self.tableWidget_planta.setGeometry(QtCore.QRect(20, 20, 771, 381))
        self.tableWidget_planta.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_planta.setAlternatingRowColors(True)
        self.tableWidget_planta.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_planta.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_planta.setObjectName("tableWidget_planta")
        self.tableWidget_planta.setColumnCount(2)
        self.tableWidget_planta.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_planta.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_planta.setHorizontalHeaderItem(1, item)
        self.tabWidget_conf.addTab(self.tab_planta, "")
        self.tab_carrito = QtWidgets.QWidget()
        self.tab_carrito.setObjectName("tab_carrito")
        self.tableWidget_carrito = QtWidgets.QTableWidget(self.tab_carrito)
        self.tableWidget_carrito.setGeometry(QtCore.QRect(20, 20, 771, 381))
        self.tableWidget_carrito.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_carrito.setAlternatingRowColors(True)
        self.tableWidget_carrito.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_carrito.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_carrito.setObjectName("tableWidget_carrito")
        self.tableWidget_carrito.setColumnCount(5)
        self.tableWidget_carrito.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_carrito.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_carrito.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_carrito.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_carrito.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_carrito.setHorizontalHeaderItem(4, item)
        self.tabWidget_conf.addTab(self.tab_carrito, "")
        self.tab_portatil = QtWidgets.QWidget()
        self.tab_portatil.setObjectName("tab_portatil")
        self.tableWidget_portatil = QtWidgets.QTableWidget(self.tab_portatil)
        self.tableWidget_portatil.setGeometry(QtCore.QRect(20, 20, 771, 381))
        self.tableWidget_portatil.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_portatil.setAlternatingRowColors(True)
        self.tableWidget_portatil.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_portatil.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_portatil.setObjectName("tableWidget_portatil")
        self.tableWidget_portatil.setColumnCount(9)
        self.tableWidget_portatil.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_portatil.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_portatil.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_portatil.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_portatil.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_portatil.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_portatil.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_portatil.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_portatil.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_portatil.setHorizontalHeaderItem(8, item)
        self.tabWidget_conf.addTab(self.tab_portatil, "")
        self.tab_conf = QtWidgets.QWidget()
        self.tab_conf.setObjectName("tab_conf")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_conf)
        self.groupBox_3.setGeometry(QtCore.QRect(110, 20, 321, 331))
        self.groupBox_3.setObjectName("groupBox_3")
        self.lineEdit_ies = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_ies.setGeometry(QtCore.QRect(120, 30, 181, 25))
        self.lineEdit_ies.setToolTip("")
        self.lineEdit_ies.setToolTipDuration(3)
        self.lineEdit_ies.setStatusTip("")
        self.lineEdit_ies.setWhatsThis("")
        self.lineEdit_ies.setAccessibleName("")
        self.lineEdit_ies.setAccessibleDescription("")
        self.lineEdit_ies.setInputMask("")
        self.lineEdit_ies.setText("")
        self.lineEdit_ies.setPlaceholderText("")
        self.lineEdit_ies.setClearButtonEnabled(True)
        self.lineEdit_ies.setObjectName("lineEdit_ies")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 61, 21))
        self.label_3.setObjectName("label_3")
        self.label_logo = QtWidgets.QLabel(self.groupBox_3)
        self.label_logo.setGeometry(QtCore.QRect(119, 60, 181, 181))
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap("../assets/imagenes/logo_ies.png"))
        self.label_logo.setScaledContents(True)
        self.label_logo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_logo.setObjectName("label_logo")
        self.pushButton_logo = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_logo.setGeometry(QtCore.QRect(10, 140, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_logo.setFont(font)
        self.pushButton_logo.setToolTip("")
        self.pushButton_logo.setStatusTip("")
        self.pushButton_logo.setWhatsThis("")
        self.pushButton_logo.setCheckable(False)
        self.pushButton_logo.setObjectName("pushButton_logo")
        self.checkBox_informes = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_informes.setGeometry(QtCore.QRect(10, 250, 261, 23))
        self.checkBox_informes.setChecked(False)
        self.checkBox_informes.setObjectName("checkBox_informes")
        self.checkBox_inicio = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_inicio.setGeometry(QtCore.QRect(10, 280, 261, 23))
        self.checkBox_inicio.setObjectName("checkBox_inicio")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_conf)
        self.groupBox_4.setGeometry(QtCore.QRect(450, 20, 231, 131))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setGeometry(QtCore.QRect(10, 30, 71, 21))
        self.label_6.setObjectName("label_6")
        self.spinBox_inicio = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_inicio.setGeometry(QtCore.QRect(10, 60, 101, 26))
        self.spinBox_inicio.setMinimum(2023)
        self.spinBox_inicio.setMaximum(2050)
        self.spinBox_inicio.setObjectName("spinBox_inicio")
        self.comboBox_inicio_curso = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_inicio_curso.setGeometry(QtCore.QRect(10, 90, 101, 25))
        self.comboBox_inicio_curso.setObjectName("comboBox_inicio_curso")
        self.comboBox_inicio_curso.addItem("")
        self.comboBox_inicio_curso.addItem("")
        self.comboBox_inicio_curso.addItem("")
        self.comboBox_inicio_curso.addItem("")
        self.comboBox_inicio_curso.addItem("")
        self.comboBox_inicio_curso.addItem("")
        self.comboBox_inicio_curso.addItem("")
        self.comboBox_inicio_curso.addItem("")
        self.comboBox_inicio_curso.addItem("")
        self.comboBox_inicio_curso.addItem("")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(130, 30, 71, 21))
        self.label_7.setObjectName("label_7")
        self.spinBox_fin = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_fin.setGeometry(QtCore.QRect(120, 60, 101, 26))
        self.spinBox_fin.setMinimum(2023)
        self.spinBox_fin.setMaximum(2050)
        self.spinBox_fin.setProperty("value", 2024)
        self.spinBox_fin.setObjectName("spinBox_fin")
        self.comboBox_fin_curso = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_fin_curso.setGeometry(QtCore.QRect(120, 90, 101, 25))
        self.comboBox_fin_curso.setObjectName("comboBox_fin_curso")
        self.comboBox_fin_curso.addItem("")
        self.comboBox_fin_curso.addItem("")
        self.comboBox_fin_curso.addItem("")
        self.comboBox_fin_curso.addItem("")
        self.comboBox_fin_curso.addItem("")
        self.comboBox_fin_curso.addItem("")
        self.comboBox_fin_curso.addItem("")
        self.comboBox_fin_curso.addItem("")
        self.comboBox_fin_curso.addItem("")
        self.comboBox_fin_curso.addItem("")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_conf)
        self.groupBox_5.setGeometry(QtCore.QRect(450, 150, 231, 201))
        self.groupBox_5.setFlat(False)
        self.groupBox_5.setObjectName("groupBox_5")
        self.pushButton_exportar_bd = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_exportar_bd.setGeometry(QtCore.QRect(20, 120, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_exportar_bd.setFont(font)
        self.pushButton_exportar_bd.setObjectName("pushButton_exportar_bd")
        self.pushButton_importar_bd = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_importar_bd.setGeometry(QtCore.QRect(20, 40, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_importar_bd.setFont(font)
        self.pushButton_importar_bd.setObjectName("pushButton_importar_bd")
        self.pushButton_guardar_conf = QtWidgets.QPushButton(self.tab_conf)
        self.pushButton_guardar_conf.setGeometry(QtCore.QRect(600, 370, 80, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_guardar_conf.setFont(font)
        self.pushButton_guardar_conf.setObjectName("pushButton_guardar_conf")
        self.tabWidget_conf.addTab(self.tab_conf, "")
        self.pushButton_crear_conf = QtWidgets.QPushButton(self.page_3)
        self.pushButton_crear_conf.setGeometry(QtCore.QRect(740, 430, 100, 31))
        self.pushButton_crear_conf.setObjectName("pushButton_crear_conf")
        self.toolBox_inicio.addItem(self.page_3, "")

        self.retranslateUi(Form)
        self.toolBox_inicio.setCurrentIndex(0)
        self.tabWidget_conf.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "carritos"))
        self.pushButton_acercade.setText(_translate("Form", "Acerca de"))
        self.toolBox_inicio.setItemText(self.toolBox_inicio.indexOf(self.page_5), _translate("Form", "Inicio"))
        self.groupBox.setTitle(_translate("Form", "Franjas horarias"))
        self.pushButton_1.setText(_translate("Form", "1"))
        self.pushButton_2.setText(_translate("Form", "2"))
        self.pushButton_3.setText(_translate("Form", "3"))
        self.pushButton_RECREO.setText(_translate("Form", "RECREO"))
        self.pushButton_6.setText(_translate("Form", "6"))
        self.pushButton_4.setText(_translate("Form", "4"))
        self.pushButton_5.setText(_translate("Form", "5"))
        self.plainTextEdit_1.setPlaceholderText(_translate("Form", "Sin reserva"))
        self.plainTextEdit_2.setPlaceholderText(_translate("Form", "Sin reserva"))
        self.plainTextEdit_3.setPlaceholderText(_translate("Form", "Sin reserva"))
        self.plainTextEdit_RECREO.setPlaceholderText(_translate("Form", "Sin reserva"))
        self.plainTextEdit_4.setPlaceholderText(_translate("Form", "Sin reserva"))
        self.plainTextEdit_5.setPlaceholderText(_translate("Form", "Sin reserva"))
        self.plainTextEdit_6.setPlaceholderText(_translate("Form", "Sin reserva"))
        self.label.setText(_translate("Form", "Planta"))
        self.label_2.setText(_translate("Form", "Carrito"))
        self.plainTextEdit_info.setPlaceholderText(_translate("Form", "Información"))
        self.toolBox_inicio.setItemText(self.toolBox_inicio.indexOf(self.page), _translate("Form", "Planificación y Reservas"))
        self.tableWidget_incidencia.setSortingEnabled(True)
        item = self.tableWidget_incidencia.horizontalHeaderItem(0)
        item.setText(_translate("Form", "incidencia_id"))
        item = self.tableWidget_incidencia.horizontalHeaderItem(1)
        item.setText(_translate("Form", "portatil_id"))
        item = self.tableWidget_incidencia.horizontalHeaderItem(2)
        item.setText(_translate("Form", "profesor_id"))
        item = self.tableWidget_incidencia.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Incidencia"))
        item = self.tableWidget_incidencia.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Planta"))
        item = self.tableWidget_incidencia.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Carrito"))
        item = self.tableWidget_incidencia.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Portátil"))
        item = self.tableWidget_incidencia.horizontalHeaderItem(7)
        item.setText(_translate("Form", "Estado Portátil"))
        item = self.tableWidget_incidencia.horizontalHeaderItem(8)
        item.setText(_translate("Form", "Fecha"))
        item = self.tableWidget_incidencia.horizontalHeaderItem(9)
        item.setText(_translate("Form", "Hora"))
        item = self.tableWidget_incidencia.horizontalHeaderItem(10)
        item.setText(_translate("Form", "Estado"))
        item = self.tableWidget_incidencia.horizontalHeaderItem(11)
        item.setText(_translate("Form", "fecha_id"))
        item = self.tableWidget_incidencia.horizontalHeaderItem(12)
        item.setText(_translate("Form", "horario_id"))
        self.pushButton_crear_incid.setText(_translate("Form", "CREAR INCIDENCIA"))
        self.toolBox_inicio.setItemText(self.toolBox_inicio.indexOf(self.page_2), _translate("Form", "Incidencias"))
        self.toolBox_inicio.setItemText(self.toolBox_inicio.indexOf(self.page_4), _translate("Form", "Informes"))
        self.tableWidget_profesorado.setSortingEnabled(True)
        item = self.tableWidget_profesorado.horizontalHeaderItem(0)
        item.setText(_translate("Form", "profesor_id"))
        item = self.tableWidget_profesorado.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Nombre del profesor/a"))
        self.tabWidget_conf.setTabText(self.tabWidget_conf.indexOf(self.tab_profesorado), _translate("Form", "Profesorado"))
        self.tableWidget_planta.setSortingEnabled(True)
        item = self.tableWidget_planta.horizontalHeaderItem(0)
        item.setText(_translate("Form", "planta_id"))
        item = self.tableWidget_planta.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Nombre de planta de edificio"))
        self.tabWidget_conf.setTabText(self.tabWidget_conf.indexOf(self.tab_planta), _translate("Form", "Planta"))
        self.tableWidget_carrito.setSortingEnabled(True)
        item = self.tableWidget_carrito.horizontalHeaderItem(0)
        item.setText(_translate("Form", "carrito_id"))
        item = self.tableWidget_carrito.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Carrito"))
        item = self.tableWidget_carrito.horizontalHeaderItem(2)
        item.setText(_translate("Form", "planta_id"))
        item = self.tableWidget_carrito.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Planta"))
        item = self.tableWidget_carrito.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Observaciones"))
        self.tabWidget_conf.setTabText(self.tabWidget_conf.indexOf(self.tab_carrito), _translate("Form", "Carrito"))
        self.tableWidget_portatil.setSortingEnabled(True)
        item = self.tableWidget_portatil.horizontalHeaderItem(0)
        item.setText(_translate("Form", "portatil_id"))
        item = self.tableWidget_portatil.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Marca"))
        item = self.tableWidget_portatil.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Nº serie"))
        item = self.tableWidget_portatil.horizontalHeaderItem(3)
        item.setText(_translate("Form", "carrito_id"))
        item = self.tableWidget_portatil.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Carrito"))
        item = self.tableWidget_portatil.horizontalHeaderItem(5)
        item.setText(_translate("Form", "planta_id"))
        item = self.tableWidget_portatil.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Planta"))
        item = self.tableWidget_portatil.horizontalHeaderItem(7)
        item.setText(_translate("Form", "Estado"))
        item = self.tableWidget_portatil.horizontalHeaderItem(8)
        item.setText(_translate("Form", "Observaciones"))
        self.tabWidget_conf.setTabText(self.tabWidget_conf.indexOf(self.tab_portatil), _translate("Form", "Portátil"))
        self.groupBox_3.setTitle(_translate("Form", "Datos Generales del IES"))
        self.label_3.setText(_translate("Form", "Nombre"))
        self.pushButton_logo.setText(_translate("Form", "Logo"))
        self.checkBox_informes.setText(_translate("Form", "Aplicar el logo a los informes"))
        self.checkBox_inicio.setText(_translate("Form", "Aplicar el logo a la ventana de inicio"))
        self.groupBox_4.setTitle(_translate("Form", "Curso escolar"))
        self.label_6.setText(_translate("Form", "inicio"))
        self.comboBox_inicio_curso.setItemText(0, _translate("Form", "Septiembre"))
        self.comboBox_inicio_curso.setItemText(1, _translate("Form", "Octubre"))
        self.comboBox_inicio_curso.setItemText(2, _translate("Form", "Noviembre"))
        self.comboBox_inicio_curso.setItemText(3, _translate("Form", "Diciembre"))
        self.comboBox_inicio_curso.setItemText(4, _translate("Form", "Enero"))
        self.comboBox_inicio_curso.setItemText(5, _translate("Form", "Febrero"))
        self.comboBox_inicio_curso.setItemText(6, _translate("Form", "Marzo"))
        self.comboBox_inicio_curso.setItemText(7, _translate("Form", "Abril"))
        self.comboBox_inicio_curso.setItemText(8, _translate("Form", "Mayo"))
        self.comboBox_inicio_curso.setItemText(9, _translate("Form", "Junio"))
        self.label_7.setText(_translate("Form", "Fin"))
        self.comboBox_fin_curso.setItemText(0, _translate("Form", "Junio"))
        self.comboBox_fin_curso.setItemText(1, _translate("Form", "Septiembre"))
        self.comboBox_fin_curso.setItemText(2, _translate("Form", "Octubre"))
        self.comboBox_fin_curso.setItemText(3, _translate("Form", "Noviembre"))
        self.comboBox_fin_curso.setItemText(4, _translate("Form", "Diciembre"))
        self.comboBox_fin_curso.setItemText(5, _translate("Form", "Enero"))
        self.comboBox_fin_curso.setItemText(6, _translate("Form", "Febrero"))
        self.comboBox_fin_curso.setItemText(7, _translate("Form", "Marzo"))
        self.comboBox_fin_curso.setItemText(8, _translate("Form", "Abril"))
        self.comboBox_fin_curso.setItemText(9, _translate("Form", "Mayo"))
        self.groupBox_5.setTitle(_translate("Form", "Operaciones especiales"))
        self.pushButton_exportar_bd.setText(_translate("Form", "Exportar"))
        self.pushButton_importar_bd.setText(_translate("Form", "Importar"))
        self.pushButton_guardar_conf.setText(_translate("Form", "GUARDAR"))
        self.tabWidget_conf.setTabText(self.tabWidget_conf.indexOf(self.tab_conf), _translate("Form", "Aplicación"))
        self.pushButton_crear_conf.setText(_translate("Form", "CREAR"))
        self.toolBox_inicio.setItemText(self.toolBox_inicio.indexOf(self.page_3), _translate("Form", "Configuración"))
