# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'profesorado.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Profesorado(object):
    def setupUi(self, Dialog_Profesorado):
        Dialog_Profesorado.setObjectName("Dialog_Profesorado")
        Dialog_Profesorado.resize(362, 311)
        Dialog_Profesorado.setMinimumSize(QtCore.QSize(362, 311))
        Dialog_Profesorado.setMaximumSize(QtCore.QSize(362, 311))
        self.pushButton_reservar = QtWidgets.QPushButton(Dialog_Profesorado)
        self.pushButton_reservar.setGeometry(QtCore.QRect(10, 230, 101, 61))
        self.pushButton_reservar.setDefault(True)
        self.pushButton_reservar.setObjectName("pushButton_reservar")
        self.pushButton_borrar = QtWidgets.QPushButton(Dialog_Profesorado)
        self.pushButton_borrar.setGeometry(QtCore.QRect(120, 230, 111, 61))
        self.pushButton_borrar.setAutoFillBackground(False)
        self.pushButton_borrar.setFlat(False)
        self.pushButton_borrar.setObjectName("pushButton_borrar")
        self.tableWidget_profesorado = QtWidgets.QTableWidget(Dialog_Profesorado)
        self.tableWidget_profesorado.setGeometry(QtCore.QRect(10, 20, 341, 192))
        self.tableWidget_profesorado.setMinimumSize(QtCore.QSize(341, 192))
        self.tableWidget_profesorado.setMaximumSize(QtCore.QSize(341, 192))
        self.tableWidget_profesorado.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget_profesorado.setAlternatingRowColors(True)
        self.tableWidget_profesorado.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_profesorado.setColumnCount(2)
        self.tableWidget_profesorado.setObjectName("tableWidget_profesorado")
        self.tableWidget_profesorado.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_profesorado.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_profesorado.setHorizontalHeaderItem(1, item)
        self.tableWidget_profesorado.verticalHeader().setSortIndicatorShown(True)
        self.pushButton_cancelar = QtWidgets.QPushButton(Dialog_Profesorado)
        self.pushButton_cancelar.setGeometry(QtCore.QRect(240, 230, 111, 61))
        self.pushButton_cancelar.setAutoFillBackground(False)
        self.pushButton_cancelar.setFlat(False)
        self.pushButton_cancelar.setObjectName("pushButton_cancelar")

        self.retranslateUi(Dialog_Profesorado)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Profesorado)

    def retranslateUi(self, Dialog_Profesorado):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Profesorado.setWindowTitle(_translate("Dialog_Profesorado", "Reservar"))
        self.pushButton_reservar.setText(_translate("Dialog_Profesorado", "Reservar"))
        self.pushButton_borrar.setText(_translate("Dialog_Profesorado", "Borrar\n"
" Reserva"))
        self.tableWidget_profesorado.setSortingEnabled(True)
        item = self.tableWidget_profesorado.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_Profesorado", "ID"))
        item = self.tableWidget_profesorado.horizontalHeaderItem(1)
        item.setText(_translate("Dialog_Profesorado", "Profesorado"))
        self.pushButton_cancelar.setText(_translate("Dialog_Profesorado", "Cancelar"))
